apiVersion: v1
kind: Service
metadata:
  name: go-port
spec:
  type: NodePort 
  ports:
  - port: 8080
  selector:
    app: go

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: go
  name: go
spec:
  ports:
  - port: 8080
  selector:
    app: go

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  labels:
    app: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: pengdevs/sample:golang
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: KTOR_HOST
          value: "ktor:8080"

